const ShellActionTypes = {
    SHELL_SIGN_IN: "SHELL_SIGN_IN",
    SHELL_SIGN_OUT: "SHELL_SIGN_OUT",
    SHELL_AUTHENTICATE: "SHELL_AUTHENTICATE",
    SHELL_SHOW_TILES: "SHELL_SHOW_TILES",
    SHELL_SHOW_CONFIGURATION: "SHELL_SHOW_CONFIGURATION",
    SHELL_CANCEL_CONFIGURATION: "SHELL_CANCEL_CONFIGURATION",
    SHELL_ADD_TILE: "SHELL_CREATE_TILE",
    SHELL_ADD_TILE_SUCCESS: "SHELL_ADD_TILE_SUCCESS",
    SHELL_ADD_TILE_FAILURE: "SHELL_ADD_TILE_FAILURE",
    SHELL_UPDATE_TILE: "SHELL_UPDATE_TILE",
    SHELL_UPDATE_TILE_SUCCESS: "SHELL_UPDATE_TILE_SUCCESS",
    SHELL_UPDATE_TILE_FAILURE: "SHELL_UPDATE_TILE_FAILURE",
    SHELL_REFRESH_DASHBOARD: "SHELL_REFRESH_DASHBOARD",
    SHELL_REFRESH_DASHBOARD_SUCCESS: "SHELL_REFRESH_DASHBOARD_SUCCESS",
    SHELL_REFRESH_DASHBOARD_FAILURE: "SHELL_REFRESH_DASHBOARD_FAILURE",
    SHELL_REFRESH_TILE_CONTENT: "SHELL_REFRESH_TILE_CONTENT",
    SHELL_REFRESH_TILE_CONTENT_SUCCESS: "SHELL_REFRESH_TILE_CONTENT_SUCCESS",
    SHELL_REFRESH_TILE_CONTENT_FAILURE: "SHELL_REFRESH_TILE_CONTENT_FAILURE",
    SHELL_DELETE_TILE: "SHELL_DELETE_TILE",
    SHELL_DELETE_TILE_SUCCESS: "SHELL_DELETE_TILE_SUCCESS",
    SHELL_DELETE_TILE_FAILURE: "SHELL_DELETE_TILE_FAILURE"
};

export default ShellActionTypes;