const ShellActionTypes = {
    SHELL_SIGN_IN: "SHELL_SIGN_IN",
    SHELL_SIGN_OUT: "SHELL_SIGN_OUT",
    SHELL_AUTHENTICATE: "SHELL_AUTHENTICATE",
    SHELL_SHOW_TILES: "SHELL_SHOW_TILES",
    SHELL_SHOW_CONFIGURATION: "SHELL_SHOW_CONFIGURATION",
    SHELL_CANCEL_CONFIGURATION: "SHELL_CANCEL_CONFIGURATION",
    SHELL_ADD_TILE: "SHELL_ADD_TILE"
};

export default ShellActionTypes;